/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "primary-fixed": "#cfe5ff",
        "surface-container-lowest": "#010e24",
        "tertiary": "#3ce36a",
        "on-secondary": "#20304f",
        "primary-container": "#00a3ff",
        "surface-container": "#112036",
        "on-tertiary-fixed": "#002108",
        "secondary-container": "#374767",
        "surface-container-high": "#1c2a41",
        "on-error": "#690005",
        "secondary-fixed-dim": "#b6c6ed",
        "on-background": "#d6e3ff",
        "inverse-primary": "#00629d",
        "on-tertiary-container": "#003e14",
        "inverse-surface": "#d6e3ff",
        "surface-dim": "#041329",
        "primary": "#98cbff",
        "secondary-fixed": "#d8e2ff",
        "outline-variant": "#3f4852",
        "on-surface": "#d6e3ff",
        "on-tertiary": "#003912",
        "on-primary": "#003354",
        "on-secondary-container": "#a5b5db",
        "surface-variant": "#27354c",
        "error": "#ffb4ab",
        "on-primary-container": "#00375a",
        "tertiary-fixed": "#69ff87",
        "background": "#041329",
        "surface-container-highest": "#27354c",
        "on-primary-fixed": "#001d33",
        "surface": "#041329",
        "surface-bright": "#2c3951",
        "surface-container-low": "#0d1c32",
        "on-surface-variant": "#bec7d4",
        "primary-fixed-dim": "#98cbff",
        "on-secondary-fixed": "#091b39",
        "outline": "#88919d",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#00531e",
        "tertiary-container": "#00b54a",
        "surface-tint": "#98cbff",
        "inverse-on-surface": "#233148",
        "tertiary-fixed-dim": "#3ce36a",
        "secondary": "#b6c6ed",
        "on-primary-fixed-variant": "#004a77",
        "on-secondary-fixed-variant": "#374767",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
